import InputForm from "@/components/InputForm";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Home|Todo Application",
  description: "Generated by create next app",
};

const Homepage = () => {
  return <div>{/* <InputForm /> */}</div>;
};

export default Homepage;
